### ISSUE TITLE
Project Proposal Discussion Thread

### ISSUE THREAD

**Issue by ChadNeald** [UBC-MDS/bc_election_turnout#10]

**Comment by ChadNeald** [comment]
- Choose dataset
- Identify one main research question
- Make a plan to anaylize the data
- At least one EDA
- A plan on how to share/communicate our findings.

**Comment by ChadNeald** [comment]
Possible data set/research question. https://open.canada.ca/data/en/dataset/261c32ab-4cfd-4f81-9dea-7b64065690dc Covid dataset that has data on the cases by day for each province and territory in Canada.

**Comment by rtaph** [comment]
Scratchpad of ideas brainstormed during our team meeting: 

- **Idea 1:** Research question: Do B.C. electoral districts that are more competitive have greater voter turnout? 
	- Dataset: BC Elections past data: https://elections.bc.ca/resources/results/provincial-election-results/
- **Idea 2:** Something related to music.
	- Data: https://library.duke.edu/music/resources/databases
- **Idea 3:** Using ML to attempt to reverse engineer a (bag of words) model of Twitter’s algorithm for flagging/muting false tweets.
	- Data: twitter feeds from politicians, maybe other tweets from influencers
	- Limitations: may not exist in tabular format without an API or without scraping.
- **Idea 4:** Predicting incidents of violence based on hate speech on social media
	- Dataset : http://hatespeechdata.com/
	- Limitations: Probably too difficult
- **Idea 5:** Research questions: Are certain demographic features of counties predictive of how people voted on Uber/Lyft’s prop 22 in California? 
- **Idea 6:** Predicting what party a politician is from based on their speeches in parliament (multiclass bag-of-words classifier). What words are particularly predictive?
	- Data: Hansard
- **Idea 7:** Something using fivethirtyeight’s datasets
	- Data: https://data.fivethirtyeight.com/ 
- **Idea 8:** Predicting the probability of getting a parking ticket in Vancouver:
	- Data: https://opendata.vancouver.ca/explore/dataset/parking-tickets-2017-2019/information/
	- Limitations: Data only has positive classes. Would need to find another source of data to get a sense of prevalence of cars parked in different areas. Could simplify the problem by predicting the type of infraction, conditional on there being an infraction. Could also use data on parking meters to compliment this.
- **Idea 9:** Predicting some BC tourism statistics: 
	- Data: any of these: https://www2.gov.bc.ca/gov/content/data/statistics/business-industry-trade/industry/tourism 
- **Idea 10:** Predict which of 22 Vancouver neighbourhoods someone lives in, based on demographic information like language, income, family size, etc.
	- Data: Census local area profiles 2016

**Comment by yuanxiongbear** [comment]
Working with Kamal for the project proposal. I updated project proposal in README.md file based on Kamal's draft this morning (in my fork). Link: https://github.com/yuanxiongbear/bc_election_turnout/blob/yxiong/README.md
