### ISSUE TITLE
Script 3: Data Viz

### ISSUE THREAD

**Issue by rtaph** [UBC-MDS/bc_election_turnout#26]
A third script which creates exploratory data visualization(s) and table(s) that are useful to help the reader/consumer understand that dataset. This should take two arguments:
- a path/filename pointing to the data
- a path/filename prefix where to write the figure to and what to call it (e.g., `results/this_eda.png`)

**Comment by yuanxiongbear** [comment]
This is my script 3. I haven't issued a pull request yet. And it is in my fork. Here is the link
https://github.com/yuanxiongbear/bc_election_turnout/blob/yxiong/src/processed_data_to_plots.R
Please review it and let me know if I did it correctly. 

Basically my script takes 2 input (file path input, and file path output). I read the input using read_csv, and then generate 3 plots (violin, correlation matrix and scatter plot) using the code that Raf developed. And then I save each image using the output file path. 

Thank you.
