### ISSUE TITLE
EDA code and figures

### ISSUE THREAD

**Issue by abaghela** [UBC-MDS/bc_election_turnout#35]
One figure the text was too big and became hard to read. Nonetheless the script was excellent and great use of dplyr code and the pipe.

**Comment by rtaph** [comment]
Thank you for the feedback @abaghela!

Are you referencing the x-axis labels in the violin plot in [eda/eda_election_turnout.pdf](https://github.com/UBC-MDS/bc_election_turnout/blob/main/eda/eda_election_turnout.pdf), or something else?

Thanks!

**Comment by ChadNeald** [comment]
Maybe we can just change the violin plot x axis to the years (2005, 2009, etc.). Should this also be moved to the y axis title "Percentage of Eligible Voters Who Partcipated in ED" instead of Density?

**Comment by rtaph** [comment]
Quite right, @ChadNeald, and great suggestions. Let me submit a PR for that now.
