### ISSUE TITLE
Renaming Scripts

### ISSUE THREAD

**Issue by rtaph** [UBC-MDS/bc_election_turnout#45]
Team,

What do you think about renaming our scripts to:

- download_data.R (stays as is)
- clean_data.R
- make_figures.R
- perform_statistical_test.R

**Comment by kmoravej** [comment]
Sounds good. I'll change it and send a pull request. We should remember to change the names in bash file and also the Usage inside the code.

**Comment by ChadNeald** [comment]
Yup that makes sense to me.
