### ISSUE TITLE
Split out figure creation into separate scripts

### ISSUE THREAD

**Issue by rtaph** [UBC-MDS/bc_election_turnout#51]
Now that we are moving to using Make, I think it would make sense to split out our `make_figures.R` script into a separate script for each plot.

**Comment by yuanxiongbear** [comment]
Sounds good. I can start working on it today and then I will send in pull request tonight. The check list includes: 
1. split the make_figures.R into four scripts and once plot per script
2. modify makefile accordingly. 
Images saved locations and names will not be changed. 

If I missed anything please let me know.
