### ISSUE TITLE
Milestone 2 General Feedback

### ISSUE THREAD

**Issue by ahofmann4** [UBC-MDS/bc_election_turnout#59]
Hello BC Elections Turnout Group!

Well done on your project!! I have very few suggestions, and your code ran smoothly.

Suggestions for Report:
1) missing names, and date last edited.
2) the transition between figures 1 and 2 is a bit jumbled. I am not sure where the Soure:Elections BC Open Data phrase is supposed to be associated with. Some more space between the figures would help

**Comment by rtaph** [comment]
Feedback Implementation

- [x] Add names and date to the main report
	- See d235c51 in #69 
- [X] Fix the transition between figures
	- See 84e992f in #69. I used a grey background theme to make it clearer what is and is not in the figure, reorganized the section to not have them back-to-back, and tidied up the confusion with the figure auto-naming in PDF.
