### ISSUE TITLE
Peer Feedback (Jacob McFarlane)

### ISSUE THREAD

**Issue by JacobMcFarlane** [UBC-MDS/bc_election_turnout#67]
Quite an interesting project and a fun read!

It seems like the other peer reviewers gave your code a solid going through, so I'll focus mainly on the report. The only thing I saw code wise was that one of your 'main' functions in a docopt script wasn't named main. Not a big thing but naming it main might make the code a little more readable.

For Figure 1, you may want to consider either removing the grey error shading around your line of best fit or specifying the method that was used to generate the error estimate. It's a little bit of a mystery as is unless I missed something elsewhere in your report. You might also consider capitalizing the title or not capitalizing the axis labels but that's really a stylistic preference.

This is super nitpicky, but in the section below it might be worth stating that your measure of district competitiveness is a proxy measurement for competitiveness as discussed by political pundits:

>While the statistical test above does not make any causal claim, the findings do align with the way many political pundits think about certain causal relationships in elections. Namely, the common thinking is that rivaling political parties, informed by pre-election polls, invest more time and money in campaigning and “getting out the vote” in districts they think might swing the election.

Competitiveness defined as the voter share of the runner up minus the winner share of the runner up by definition can't be a cause of voter turnout since it doesn't really exist before voting happens. That's competitiveness as you operationalized it and as used with "the statistical test above" but that's not the same competitiveness in the accepted theories about causal relationships in elections. You are using the voter share to estimate how competitive a district is, in a sense. Again, it's probably more nitpicky than you need to be here but I think acknowledging that in your discussion section would make this a stronger report.

All in all, I'm really impressed with your end product. 

Best,
Jacob

**Comment by rtaph** [comment]
Thanks, Jacob!

That all makes sense. The grey band is a 95% confidence interval around the regression line, which we can probably express equivalently as a CI around the correlation coefficient. We'll either remove it or add a subtitle to explain what that band is.

**Comment by rtaph** [comment]
Feedback Implementation

- [x] rename `docopt` function to main
- [x] Explain error band in scatterplot or remove it
- [x] Clarify language/interpretation of competitiveness

**Comment by kmoravej** [comment]
#73 
- [x] rename `docopt` function to main
- [x] Explain error band in scatterplot or remove it
- [x] Clarify language/interpretation of competitiveness
