### ISSUE TITLE
Create a Download Script

### ISSUE THREAD

**Issue by ChadNeald** [UBC-MDS/bc_election_turnout#8]

**Comment by ChadNeald** [comment]
Reviewer: Raf

**Comment by rtaph** [comment]
In case 2020 election results prove to be too technically difficult (HTML results or PDFs), here are links I found to previous years' CSV files:

Election Results: https://catalogue.data.gov.bc.ca/dataset/provincial-voting-results
Voter Turnout: https://catalogue.data.gov.bc.ca/dataset/provincial-voter-participation-by-age-group

**Comment by rtaph** [comment]
My implementation of the download script is available on my fork's dev branch [here](https://github.com/rtaph/bc_election_turnout/blob/dev/src/download_csv_url.R).

**Comment by ChadNeald** [comment]
If anyone wants to compare, here's my download script. I may add some testthat functions tomorrow, but the gist of it is done [download_script](https://github.com/ChadNeald/bc_election_turnout/blob/download_script_r/download_data.R)

**Comment by ChadNeald** [comment]
I updated my download script to make it more general. Thanks @rtaph for the feedback much appreciated! New script can be found [here](https://github.com/ChadNeald/bc_election_turnout/blob/download_script_r/download_data.R) We may not even use this version, but I'm curious if it works as intended on other peoples machines so if anyone has time let me know if it seems to work for them or not!

**Comment by yuanxiongbear** [comment]
I also updated my download script in my fork. Here is the link: https://github.com/yuanxiongbear/bc_election_turnout/tree/yxiong/src

I am still learning how to use here (so it is missing). The way how I process the data is:
1. download the two csv files. 
2. filter based on year = 2017 (I think that was the original plan)
3. use the participation csv to calculate vote rate (vote/registered voters) based on ED
4. use the vote result to calculate comparability based on ED. 
5. Merge the data and produce final dataframe that is ready for plotting. 

This is very very basic data wrangling and I know it sucks. But I am here to learn. Thank you.
