### ISSUE TITLE
EDA Analysis for Milestone 1

### ISSUE THREAD

**Issue by ChadNeald** [UBC-MDS/bc_election_turnout#9]

**Comment by ChadNeald** [comment]
Reviewer: Yuan

**Comment by rtaph** [comment]
Dear team, my own EDA is available [here](https://github.com/rtaph/bc_election_turnout/blob/dev/eda). Because it lives my own personal dev branch and is not in PR, I have added knitted PDFs and HTMLs which may make it easier to review.

**Comment by yuanxiongbear** [comment]
I uploaded the data and plot into my own folk. link: https://github.com/yuanxiongbear/bc_election_turnout/tree/yxiong/EDA
